version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: stomology_dep
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL/stomology_dep.sql:/docker-entrypoint-initdb.d/stomology_dep.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py-backend
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: stomology_dep

volumes:
  mysql_data:

